version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: real-estate-crm-db
    environment:
      POSTGRES_DB: real_estate_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/schema/db/policies:/docker-entrypoint-initdb.d
    networks:
      - real-estate-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: real-estate-crm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - real-estate-network
    restart: unless-stopped

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-estate-crm-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/real_estate_crm?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
      - SESSION_SECRET=your-session-secret-key
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - real-estate-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: real-estate-crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - real-estate-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  real-estate-network:
    driver: bridge
