real_estate_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      port: "{{ env_var('DB_PORT', 5432) }}"
      dbname: "{{ env_var('DB_NAME', 'real_estate_crm') }}"
      schema: analytics_dev
      threads: 4
      keepalives_idle: 0
      search_path: analytics_dev, public
      
    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      user: "{{ env_var('PROD_DB_USER') }}"
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      port: "{{ env_var('PROD_DB_PORT', 5432) }}"
      dbname: "{{ env_var('PROD_DB_NAME') }}"
      schema: analytics_prod
      threads: 8
      keepalives_idle: 0
      search_path: analytics_prod, public
      
    bigquery:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET', 'real_estate_analytics') }}"
      keyfile: "{{ env_var('BQ_KEYFILE') }}"
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      priority: interactive
