import { createContext, useCallback, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

interface LanguageContextType {
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
  language: SupportedLanguage;
  setLanguage: (language: SupportedLanguage) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export type SupportedLanguage = 'ar' | 'en';

const LANGUAGE_STORAGE_KEY = 'crm-language';

const englishTranslations: Record<string, string> = {
  'nav.dashboard': 'Dashboard',
  'nav.leads': 'Leads',
  'nav.properties': 'Properties',
  'nav.pipeline': 'Pipeline',
  'nav.clients': 'Clients',
  'nav.reports': 'Reports',
  'nav.notifications': 'Notifications',
  'nav.campaigns': 'Campaigns',
  'nav.customers': 'Customer Registry',
  'nav.customer_requests': 'Customer Requests',
  'nav.admin_requests': 'Internal Requests',
  'nav.agencies': 'Agencies',
  'nav.post_listing': 'Post Listing',
  'nav.favorites': 'Favorites',
  'nav.saved_searches': 'Saved Searches',
  'nav.compare': 'Compare',
  'nav.marketing_requests': 'Marketing Requests',
  'nav.cms': 'Content Studio',
  'nav.moderation': 'Listing Moderation',
  'nav.settings': 'Settings',
  'nav.system_title': 'Real Estate Management System',
  'nav.logout': 'Log out',
  'nav.welcome': 'Welcome',
  'nav.search': 'Search for a property',
  'nav.listings': 'Listings',
  'nav.login': 'Log in',
  'nav.signup': 'Create account',
  'app.subtitle': 'Aqarkom Platform',
  'auth.logout': 'Log out',
  'auth.loggedIn': 'Welcome back',
  'header.toggleSidebarOpen': 'Open navigation menu',
  'header.toggleSidebarClose': 'Close navigation menu',
  'header.lightMode': 'Activate light mode',
  'header.darkMode': 'Activate dark mode',
  'header.notifications': 'Notifications',
  'header.languageToggle': 'Switch language',
  'header.language.ar': 'Arabic',
  'header.language.en': 'English',
  'sidebar.brandAlt': 'Aqarkom',
  'sidebar.salesManagement': 'Sales Management',
  'sidebar.customerManagement': 'Customer Management',
  'sidebar.marketplace': 'Properties & Marketplace',
  'sidebar.marketingContent': 'Marketing & Content',
  'sidebar.settingsSupport': 'Settings & Support',
  'dashboard.title': 'Dashboard',
  'dashboard.loading': 'Loading dashboard...',
  'dashboard.total_leads': 'Total leads',
  'dashboard.active_properties': 'Active properties',
  'dashboard.deals_in_pipeline': 'Deals in pipeline',
  'dashboard.monthly_revenue': 'Monthly revenue',
  'dashboard.recent_leads': 'New leads',
  'dashboard.todays_activities': "Today's activities",
  'dashboard.no_activities_today': 'No activities today',
  'dashboard.pipeline_overview': 'Pipeline overview',
  'leads.title': 'Lead management',
  'leads.add_lead': 'Add lead',
  'leads.first_name': 'First name',
  'leads.last_name': 'Last name',
  'leads.email': 'Email',
  'leads.phone': 'Phone number',
  'leads.lead_source': 'Lead source',
  'leads.interest_type': 'Interest type',
  'leads.budget_range': 'Budget range',
  'leads.status': 'Status',
  'leads.notes': 'Notes',
  'leads.search_placeholder': 'Search leads...',
  'leads.whatsapp': 'WhatsApp',
  'leads.activities': 'Activities',
  'properties.title': 'Property management',
  'properties.add_property': 'Add property',
  'properties.property_title': 'Property title',
  'properties.description': 'Description',
  'properties.address': 'Address',
  'properties.city': 'City',
  'properties.state': 'Region',
  'properties.zip_code': 'Postal code',
  'properties.price': 'Price',
  'properties.property_type': 'Property type',
  'properties.bedrooms': 'Bedrooms',
  'properties.bathrooms': 'Bathrooms',
  'properties.square_feet': 'Area (m²)',
  'properties.features': 'Features',
  'properties.photo_url': 'Photo URL',
  'properties.search_placeholder': 'Search properties...',
  'form.save': 'Save',
  'form.cancel': 'Cancel',
  'form.submit': 'Submit',
  'form.close': 'Close',
  'form.edit': 'Edit',
  'form.delete': 'Delete',
  'form.add': 'Add',
  'form.required': 'Required',
  'form.search': 'Search...',
  'form.view_all': 'View all',
  'status.new': 'New',
  'status.qualified': 'Qualified',
  'status.showing': 'Showing',
  'status.negotiation': 'Negotiation',
  'status.closed': 'Closed',
  'status.lost': 'Lost',
  'status.active': 'Active',
  'status.pending': 'Pending',
  'status.sold': 'Sold',
  'interest.buying': 'Buying',
  'interest.selling': 'Selling',
  'interest.renting': 'Renting',
  'interest.investment': 'Investment',
  'property_type.house': 'House',
  'property_type.apartment': 'Apartment',
  'property_type.villa': 'Villa',
  'property_type.commercial': 'Commercial',
  'property_type.land': 'Land',
  'message.success': 'Completed successfully',
  'message.error': 'An error occurred',
  'message.confirm_delete': 'Do you want to delete this item?',
  'whatsapp.send_message': 'Send WhatsApp message',
  'whatsapp.message_placeholder': 'Type your message...',
  'whatsapp.send': 'Send',
  'reports.title': 'Reports & Analytics',
  'reports.lead_conversion': 'Lead conversion rate',
  'reports.avg_deal_size': 'Average deal size',
  'reports.commission_rate': 'Commission rate',
  'reports.closed_deals': 'Closed deals',
  'reports.total_pipeline_value': 'Total pipeline value',
  'reports.deal_pipeline_summary': 'Deal pipeline summary',
  'reports.property_analytics': 'Property analytics',
  'reports.performance_metrics': 'Performance metrics',
  'reports.total_deals': 'Total deals',
  'reports.active_deals': 'Active deals',
  'reports.total_properties': 'Total properties',
  'reports.active_listings': 'Active listings',
  'reports.sold_properties': 'Sold properties',
  'reports.average_price': 'Average price',
  'public.listings_title': 'Available listings',
  'public.listings_sub': 'Explore the latest listings with advanced filtering',
  'public.featured_title': 'Featured properties',
  'public.latest_title': 'Latest listings',
  'public.favorites_title': 'Favorite properties',
  'public.compare_title': 'Compare properties',
  'public.post_title': 'Post a property',
  'public.moderation_title': 'Moderation queue',
  'public.agencies_title': 'Agencies directory',
  'public.agency_title': 'Agency profile',
  'public.agent_title': 'Agent profile',
  'public.footer_rights': '© All rights reserved',
  'admin.sidebar.overview': 'Overview',
  'admin.sidebar.overview.dashboard': 'Main dashboard',
  'admin.sidebar.overview.statistics': 'Global statistics',
  'admin.sidebar.overview.recent_activity': 'Recent activity',
  'admin.sidebar.user_management': 'User management',
  'admin.sidebar.user_management.all_users': 'All users',
  'admin.sidebar.user_management.active_users': 'Active users',
  'admin.sidebar.user_management.pending_users': 'Pending users',
  'admin.sidebar.user_management.user_roles': 'User roles',
  'admin.sidebar.user_management.user_permissions': 'User permissions',
  'admin.sidebar.role_management': 'Role management',
  'admin.sidebar.role_management.roles_list': 'Roles list',
  'admin.sidebar.role_management.create_role': 'Create new role',
  'admin.sidebar.role_management.permissions': 'Manage permissions',
  'admin.sidebar.role_management.role_assignments': 'Role assignments',
  'admin.sidebar.organization_management': 'Organization management',
  'admin.sidebar.organization_management.organizations_list': 'Organizations list',
  'admin.sidebar.organization_management.create_organization': 'Create organization',
  'admin.sidebar.organization_management.organization_types': 'Organization types',
  'admin.sidebar.organization_management.organization_settings': 'Organization settings',
  'admin.sidebar.revenue_management': 'Revenue & subscriptions',
  'admin.sidebar.revenue_management.overview': 'Revenue overview',
  'admin.sidebar.revenue_management.subscriptions': 'Active subscriptions',
  'admin.sidebar.revenue_management.payment_methods': 'Payment methods',
  'admin.sidebar.revenue_management.reports': 'Revenue reports',
  'admin.sidebar.revenue_management.subscription_plans': 'Subscription plans',
  'admin.sidebar.complaints_management': 'Complaints management',
  'admin.sidebar.complaints_management.all': 'All complaints',
  'admin.sidebar.complaints_management.open': 'Open complaints',
  'admin.sidebar.complaints_management.resolved': 'Resolved complaints',
  'admin.sidebar.complaints_management.categories': 'Complaint categories',
  'admin.sidebar.complaints_management.response_templates': 'Response templates',
  'admin.sidebar.integrations': 'Integrations',
  'admin.sidebar.integrations.whatsapp_settings': 'WhatsApp settings',
  'admin.sidebar.integrations.email_settings': 'Email settings',
  'admin.sidebar.integrations.sms_settings': 'SMS settings',
  'admin.sidebar.integrations.social_media': 'Social media',
  'admin.sidebar.integrations.api_integrations': 'API integrations',
  'admin.sidebar.content_management': 'Content management',
  'admin.sidebar.content_management.landing_pages': 'Landing pages',
  'admin.sidebar.content_management.articles': 'Articles',
  'admin.sidebar.content_management.media_library': 'Media library',
  'admin.sidebar.content_management.seo_settings': 'SEO settings',
  'admin.sidebar.content_management.content_templates': 'Content templates',
  'admin.sidebar.features_plans': 'Features & plans',
  'admin.sidebar.features_plans.feature_comparison': 'Feature comparison',
  'admin.sidebar.features_plans.pricing_plans': 'Pricing plans',
  'admin.sidebar.features_plans.corporate_features': 'Corporate features',
  'admin.sidebar.features_plans.individual_features': 'Individual features',
  'admin.sidebar.features_plans.feature_requests': 'Feature requests',
  'admin.sidebar.advanced_analytics': 'Advanced analytics',
  'admin.sidebar.advanced_analytics.user_analytics': 'User analytics',
  'admin.sidebar.advanced_analytics.revenue_analytics': 'Revenue analytics',
  'admin.sidebar.advanced_analytics.usage_statistics': 'Usage statistics',
  'admin.sidebar.advanced_analytics.performance_metrics': 'Performance metrics',
  'admin.sidebar.advanced_analytics.custom_reports': 'Custom reports',
  'admin.sidebar.invoicing_payments': 'Invoicing & payments',
  'admin.sidebar.invoicing_payments.invoices_list': 'Invoices list',
  'admin.sidebar.invoicing_payments.create_invoice': 'Create invoice',
  'admin.sidebar.invoicing_payments.payment_tracking': 'Payment tracking',
  'admin.sidebar.invoicing_payments.payment_methods': 'Payment methods',
  'admin.sidebar.invoicing_payments.billing_settings': 'Billing settings',
  'admin.sidebar.security_settings': 'Security',
  'admin.sidebar.security_settings.access_control': 'Access control',
  'admin.sidebar.security_settings.security_logs': 'Security logs',
  'admin.sidebar.security_settings.two_factor': 'Two-factor authentication',
  'admin.sidebar.security_settings.password_policies': 'Password policies',
  'admin.sidebar.security_settings.security_alerts': 'Security alerts',
  'admin.sidebar.notifications': 'Notifications',
  'admin.sidebar.notifications.notification_center': 'Notification center',
  'admin.sidebar.notifications.email_notifications': 'Email notifications',
  'admin.sidebar.notifications.push_notifications': 'Push notifications',
  'admin.sidebar.notifications.notification_templates': 'Notification templates',
  'admin.sidebar.notifications.notification_settings': 'Notification settings',
  'admin.sidebar.system_settings': 'System settings',
  'admin.sidebar.system_settings.general_settings': 'General settings',
  'admin.sidebar.system_settings.database_management': 'Database management',
  'admin.sidebar.system_settings.backup_restore': 'Backup & restore',
  'admin.sidebar.system_settings.system_logs': 'System logs',
  'admin.sidebar.system_settings.maintenance': 'Maintenance',
  'listing.details': 'Details',
  'listing.save': 'Save',
  'listing.compare': 'Compare',
  'listing.added': 'Added to favorites',
  'listing.save_error': 'Unable to save',
  'listing.compare_added': 'Comparison updated',
  'listing.no_photo': 'No photo',
  'listing.back': 'Back',
  'listing.report': 'Report listing',
  'saved.title': 'Saved searches',
  'saved.subtitle': 'Manage alerts and quick access',
  'saved.add': 'Add search',
  'saved.run': 'Run alerts',
  'saved.delete': 'Delete',
  'saved.none': 'No saved searches',
};

const arabicTranslations: Record<string, string> = {
  ...englishTranslations,
  'nav.dashboard': 'لوحة التحكم',
  'nav.leads': 'العملاء المحتملين',
  'nav.properties': 'العقارات',
  'nav.pipeline': 'خط الأنابيب',
  'nav.clients': 'العملاء',
  'nav.reports': 'التقارير',
  'nav.notifications': 'الإشعارات',
  'nav.campaigns': 'الحملات',
  'nav.customers': 'سجل العملاء',
  'nav.customer_requests': 'طلبات العملاء',
  'nav.admin_requests': 'الطلبات الداخلية',
  'nav.agencies': 'الوكالات',
  'nav.post_listing': 'نشر إعلان',
  'nav.favorites': 'المفضلة',
  'nav.saved_searches': 'عمليات البحث المحفوظة',
  'nav.compare': 'المقارنة',
  'nav.marketing_requests': 'طلبات التسويق',
  'nav.cms': 'استوديو المحتوى',
  'nav.moderation': 'مراجعة القوائم',
  'nav.settings': 'الإعدادات',
  'nav.system_title': 'نظام إدارة العقارات',
  'nav.logout': 'تسجيل الخروج',
  'nav.welcome': 'مرحباً',
  'nav.search': 'ابحث عن عقار',
  'nav.listings': 'العقارات',
  'nav.login': 'تسجيل الدخول',
  'nav.signup': 'إنشاء حساب',
  'app.subtitle': 'منصة عقاركم',
  'auth.logout': 'تسجيل الخروج',
  'auth.loggedIn': 'مرحباً بعودتك',
  'header.toggleSidebarOpen': 'إظهار القائمة الجانبية',
  'header.toggleSidebarClose': 'إخفاء القائمة الجانبية',
  'header.lightMode': 'تفعيل الوضع الفاتح',
  'header.darkMode': 'تفعيل الوضع الداكن',
  'header.notifications': 'الإشعارات',
  'header.languageToggle': 'تغيير اللغة',
  'header.language.ar': 'العربية',
  'header.language.en': 'الإنجليزية',
  'sidebar.brandAlt': 'عقاركم',
  'sidebar.salesManagement': 'إدارة المبيعات',
  'sidebar.customerManagement': 'إدارة العملاء',
  'sidebar.marketplace': 'العقارات والسوق',
  'sidebar.marketingContent': 'التسويق والمحتوى',
  'sidebar.settingsSupport': 'الإعدادات والدعم',
  'dashboard.title': 'لوحة التحكم',
  'dashboard.loading': 'جار تحميل لوحة التحكم...',
  'dashboard.total_leads': 'إجمالي العملاء المحتملين',
  'dashboard.active_properties': 'العقارات النشطة',
  'dashboard.deals_in_pipeline': 'الصفقات في المسار',
  'dashboard.monthly_revenue': 'الإيرادات الشهرية',
  'dashboard.recent_leads': 'العملاء المحتملون الجدد',
  'dashboard.todays_activities': 'أنشطة اليوم',
  'dashboard.no_activities_today': 'لا توجد أنشطة اليوم',
  'dashboard.pipeline_overview': 'نظرة عامة على المسار',
  'leads.title': 'إدارة العملاء المحتملين',
  'leads.add_lead': 'إضافة عميل محتمل',
  'leads.first_name': 'الاسم الأول',
  'leads.last_name': 'اسم العائلة',
  'leads.email': 'البريد الإلكتروني',
  'leads.phone': 'رقم الهاتف',
  'leads.lead_source': 'مصدر العميل',
  'leads.interest_type': 'نوع الاهتمام',
  'leads.budget_range': 'نطاق الميزانية',
  'leads.status': 'الحالة',
  'leads.notes': 'الملاحظات',
  'leads.search_placeholder': 'البحث عن العملاء المحتملين...',
  'leads.whatsapp': 'واتساب',
  'leads.activities': 'الأنشطة',
  'properties.title': 'إدارة العقارات',
  'properties.add_property': 'إضافة عقار',
  'properties.property_title': 'عنوان العقار',
  'properties.description': 'الوصف',
  'properties.address': 'العنوان',
  'properties.city': 'المدينة',
  'properties.state': 'المنطقة',
  'properties.zip_code': 'الرمز البريدي',
  'properties.price': 'السعر',
  'properties.property_type': 'نوع العقار',
  'properties.bedrooms': 'عدد الغرف',
  'properties.bathrooms': 'عدد الحمامات',
  'properties.square_feet': 'المساحة (متر مربع)',
  'properties.features': 'المميزات',
  'properties.photo_url': 'رابط الصورة',
  'properties.search_placeholder': 'البحث عن العقارات...',
  'form.save': 'حفظ',
  'form.cancel': 'إلغاء',
  'form.submit': 'إرسال',
  'form.close': 'إغلاق',
  'form.edit': 'تعديل',
  'form.delete': 'حذف',
  'form.add': 'إضافة',
  'form.required': 'مطلوب',
  'form.search': 'البحث...',
  'form.view_all': 'عرض الكل',
  'status.new': 'جديد',
  'status.qualified': 'مؤهل',
  'status.showing': 'معاينة',
  'status.negotiation': 'تفاوض',
  'status.closed': 'مغلق',
  'status.lost': 'مفقود',
  'status.active': 'نشط',
  'status.pending': 'معلق',
  'status.sold': 'مباع',
  'interest.buying': 'شراء',
  'interest.selling': 'بيع',
  'interest.renting': 'إيجار',
  'interest.investment': 'استثمار',
  'property_type.house': 'منزل',
  'property_type.apartment': 'شقة',
  'property_type.villa': 'فيلا',
  'property_type.commercial': 'تجاري',
  'property_type.land': 'أرض',
  'message.success': 'تم بنجاح',
  'message.error': 'حدث خطأ',
  'message.confirm_delete': 'هل تريد حذف هذا العنصر؟',
  'whatsapp.send_message': 'إرسال رسالة واتساب',
  'whatsapp.message_placeholder': 'اكتب رسالتك هنا...',
  'whatsapp.send': 'إرسال',
  'reports.title': 'التقارير والإحصائيات',
  'reports.lead_conversion': 'معدل تحويل العملاء',
  'reports.avg_deal_size': 'متوسط حجم الصفقة',
  'reports.commission_rate': 'معدل العمولة',
  'reports.closed_deals': 'الصفقات المغلقة',
  'reports.total_pipeline_value': 'القيمة الإجمالية للمسار',
  'reports.deal_pipeline_summary': 'ملخص مسار الصفقات',
  'reports.property_analytics': 'تحليلات العقارات',
  'reports.performance_metrics': 'مقاييس الأداء',
  'reports.total_deals': 'إجمالي الصفقات',
  'reports.active_deals': 'الصفقات النشطة',
  'reports.total_properties': 'إجمالي العقارات',
  'reports.active_listings': 'القوائم النشطة',
  'reports.sold_properties': 'العقارات المباعة',
  'reports.average_price': 'متوسط السعر',
  'public.listings_title': 'العقارات المتاحة',
  'public.listings_sub': 'استكشف أحدث العقارات مع تصفية متقدمة',
  'public.featured_title': 'عقارات مميزة',
  'public.latest_title': 'أحدث الإعلانات',
  'public.favorites_title': 'العقارات المفضلة',
  'public.compare_title': 'مقارنة العقارات',
  'public.post_title': 'نشر إعلان عقاري',
  'public.moderation_title': 'قائمة المراجعة',
  'public.agencies_title': 'الوكالات العقارية',
  'public.agency_title': 'ملف الوكالة',
  'public.agent_title': 'ملف الوسيط',
  'public.footer_rights': '© جميع الحقوق محفوظة',
  'admin.sidebar.overview': 'نظرة عامة',
  'admin.sidebar.overview.dashboard': 'لوحة التحكم الرئيسية',
  'admin.sidebar.overview.statistics': 'الإحصائيات العامة',
  'admin.sidebar.overview.recent_activity': 'النشاط الأخير',
  'admin.sidebar.user_management': 'إدارة المستخدمين',
  'admin.sidebar.user_management.all_users': 'جميع المستخدمين',
  'admin.sidebar.user_management.active_users': 'المستخدمون النشطون',
  'admin.sidebar.user_management.pending_users': 'المستخدمون المعلقون',
  'admin.sidebar.user_management.user_roles': 'أدوار المستخدمين',
  'admin.sidebar.user_management.user_permissions': 'صلاحيات المستخدمين',
  'admin.sidebar.role_management': 'إدارة الأدوار',
  'admin.sidebar.role_management.roles_list': 'قائمة الأدوار',
  'admin.sidebar.role_management.create_role': 'إنشاء دور جديد',
  'admin.sidebar.role_management.permissions': 'إدارة الصلاحيات',
  'admin.sidebar.role_management.role_assignments': 'تعيين الأدوار',
  'admin.sidebar.organization_management': 'إدارة المنظمات',
  'admin.sidebar.organization_management.organizations_list': 'قائمة المنظمات',
  'admin.sidebar.organization_management.create_organization': 'إنشاء منظمة جديدة',
  'admin.sidebar.organization_management.organization_types': 'أنواع المنظمات',
  'admin.sidebar.organization_management.organization_settings': 'إعدادات المنظمات',
  'admin.sidebar.revenue_management': 'الإيرادات والاشتراكات',
  'admin.sidebar.revenue_management.overview': 'نظرة عامة على الإيرادات',
  'admin.sidebar.revenue_management.subscriptions': 'الاشتراكات النشطة',
  'admin.sidebar.revenue_management.payment_methods': 'طرق الدفع',
  'admin.sidebar.revenue_management.reports': 'تقارير الإيرادات',
  'admin.sidebar.revenue_management.subscription_plans': 'خطط الاشتراك',
  'admin.sidebar.complaints_management': 'إدارة الشكاوى',
  'admin.sidebar.complaints_management.all': 'جميع الشكاوى',
  'admin.sidebar.complaints_management.open': 'الشكاوى المفتوحة',
  'admin.sidebar.complaints_management.resolved': 'الشكاوى المحلولة',
  'admin.sidebar.complaints_management.categories': 'فئات الشكاوى',
  'admin.sidebar.complaints_management.response_templates': 'قوالب الردود',
  'admin.sidebar.integrations': 'التكاملات',
  'admin.sidebar.integrations.whatsapp_settings': 'إعدادات WhatsApp',
  'admin.sidebar.integrations.email_settings': 'إعدادات البريد الإلكتروني',
  'admin.sidebar.integrations.sms_settings': 'إعدادات الرسائل النصية',
  'admin.sidebar.integrations.social_media': 'وسائل التواصل الاجتماعي',
  'admin.sidebar.integrations.api_integrations': 'تكاملات API',
  'admin.sidebar.content_management': 'إدارة المحتوى',
  'admin.sidebar.content_management.landing_pages': 'صفحات الهبوط',
  'admin.sidebar.content_management.articles': 'المقالات',
  'admin.sidebar.content_management.media_library': 'مكتبة الوسائط',
  'admin.sidebar.content_management.seo_settings': 'إعدادات SEO',
  'admin.sidebar.content_management.content_templates': 'قوالب المحتوى',
  'admin.sidebar.features_plans': 'الميزات والخطط',
  'admin.sidebar.features_plans.feature_comparison': 'مقارنة الميزات',
  'admin.sidebar.features_plans.pricing_plans': 'خطط الأسعار',
  'admin.sidebar.features_plans.corporate_features': 'ميزات الشركات',
  'admin.sidebar.features_plans.individual_features': 'ميزات الأفراد',
  'admin.sidebar.features_plans.feature_requests': 'طلبات الميزات',
  'admin.sidebar.advanced_analytics': 'التحليلات المتقدمة',
  'admin.sidebar.advanced_analytics.user_analytics': 'تحليلات المستخدمين',
  'admin.sidebar.advanced_analytics.revenue_analytics': 'تحليلات الإيرادات',
  'admin.sidebar.advanced_analytics.usage_statistics': 'إحصائيات الاستخدام',
  'admin.sidebar.advanced_analytics.performance_metrics': 'مقاييس الأداء',
  'admin.sidebar.advanced_analytics.custom_reports': 'التقارير المخصصة',
  'admin.sidebar.invoicing_payments': 'الفواتير والمدفوعات',
  'admin.sidebar.invoicing_payments.invoices_list': 'قائمة الفواتير',
  'admin.sidebar.invoicing_payments.create_invoice': 'إنشاء فاتورة جديدة',
  'admin.sidebar.invoicing_payments.payment_tracking': 'تتبع المدفوعات',
  'admin.sidebar.invoicing_payments.payment_methods': 'طرق الدفع',
  'admin.sidebar.invoicing_payments.billing_settings': 'إعدادات الفواتير',
  'admin.sidebar.security_settings': 'الأمان',
  'admin.sidebar.security_settings.access_control': 'التحكم في الوصول',
  'admin.sidebar.security_settings.security_logs': 'سجلات الأمان',
  'admin.sidebar.security_settings.two_factor': 'المصادقة الثنائية',
  'admin.sidebar.security_settings.password_policies': 'سياسات كلمات المرور',
  'admin.sidebar.security_settings.security_alerts': 'تنبيهات الأمان',
  'admin.sidebar.notifications': 'الإشعارات',
  'admin.sidebar.notifications.notification_center': 'مركز الإشعارات',
  'admin.sidebar.notifications.email_notifications': 'إشعارات البريد الإلكتروني',
  'admin.sidebar.notifications.push_notifications': 'الإشعارات الفورية',
  'admin.sidebar.notifications.notification_templates': 'قوالب الإشعارات',
  'admin.sidebar.notifications.notification_settings': 'إعدادات الإشعارات',
  'admin.sidebar.system_settings': 'إعدادات النظام',
  'admin.sidebar.system_settings.general_settings': 'الإعدادات العامة',
  'admin.sidebar.system_settings.database_management': 'إدارة قاعدة البيانات',
  'admin.sidebar.system_settings.backup_restore': 'النسخ الاحتياطي والاستعادة',
  'admin.sidebar.system_settings.system_logs': 'سجلات النظام',
  'admin.sidebar.system_settings.maintenance': 'الصيانة',
  'listing.details': 'تفاصيل',
  'listing.save': 'حفظ',
  'listing.compare': 'مقارنة',
  'listing.added': 'تمت الإضافة إلى المفضلة',
  'listing.save_error': 'تعذر الحفظ',
  'listing.compare_added': 'تم تحديث المقارنة',
  'listing.no_photo': 'لا توجد صورة',
  'listing.back': 'رجوع',
  'listing.report': 'الإبلاغ عن إعلان',
  'saved.title': 'عمليات البحث المحفوظة',
  'saved.subtitle': 'إدارة التنبيهات والبحث السريع',
  'saved.add': 'إضافة بحث',
  'saved.run': 'تشغيل التنبيهات',
  'saved.delete': 'حذف',
  'saved.none': 'لا توجد عمليات بحث محفوظة',
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: englishTranslations,
  ar: arabicTranslations,
};

const SUPPORTED_LANGUAGES = Object.keys(translations) as SupportedLanguage[];

const isSupportedLanguage = (value: string | null): value is SupportedLanguage =>
  value !== null && SUPPORTED_LANGUAGES.includes(value as SupportedLanguage);

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<SupportedLanguage>(() => {
    if (typeof window === 'undefined') {
      return 'ar';
    }

    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY) as SupportedLanguage | null;
    return isSupportedLanguage(stored) ? stored : 'ar';
  });

  const dir: LanguageContextType['dir'] = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    }
  }, [language]);

  useEffect(() => {
    if (typeof document === 'undefined') {
      return;
    }

    document.documentElement.lang = language;
    document.documentElement.dir = dir;
    document.body.setAttribute('dir', dir);
    document.body.classList.toggle('rtl', dir === 'rtl');
    document.body.classList.toggle('ltr', dir === 'ltr');
  }, [dir, language]);

  const t = useCallback(
    (key: string): string => translations[language]?.[key] ?? englishTranslations[key] ?? key,
    [language]
  );

  const contextValue = useMemo<LanguageContextType>(
    () => ({
      t,
      dir,
      language,
      setLanguage,
    }),
    [t, dir, language]
  );

  return <LanguageContext.Provider value={contextValue}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
