import { z } from "zod";

export const listingSchemas = {
    create: z.object({
        title: z.string().min(1),
        description: z.string().optional(),
        address: z.string().optional(),
        city: z.string().min(1),
        state: z.string().optional(),
        zipCode: z.string().optional(),
        region: z.string().optional(),
        district: z.string().optional(),
        regionId: z.coerce.number().optional(),
        cityId: z.coerce.number().optional(),
        districtId: z.coerce.number().optional(),
        price: z.union([z.coerce.number(), z.string()]),
        propertyCategory: z.string().optional(),
        propertyType: z.string().min(1),
        listingType: z.string().optional(),
        bedrooms: z.coerce.number().optional(),
        bathrooms: z.coerce.number().optional(),
        livingRooms: z.coerce.number().optional(),
        squareFeet: z.coerce.number().optional(),
        latitude: z.union([z.coerce.number(), z.string()]).optional(),
        longitude: z.union([z.coerce.number(), z.string()]).optional(),
        features: z.array(z.string()).optional(),
        ownerId: z.string().optional(),
        createdBy: z.string().optional(),
        agentId: z.string().optional(),
        organizationId: z.string().optional(),
        moderationStatus: z.string().optional(),
        status: z.string().optional(),
    }),
    update: z.object({
        title: z.string().optional(),
        description: z.string().optional(),
        address: z.string().optional(),
        city: z.string().optional(),
        state: z.string().optional(),
        zipCode: z.string().optional(),
        region: z.string().optional(),
        district: z.string().optional(),
        regionId: z.coerce.number().optional(),
        cityId: z.coerce.number().optional(),
        districtId: z.coerce.number().optional(),
        price: z.union([z.coerce.number(), z.string()]).optional(),
        propertyCategory: z.string().optional(),
        propertyType: z.string().optional(),
        listingType: z.string().optional(),
        bedrooms: z.coerce.number().optional(),
        bathrooms: z.coerce.number().optional(),
        squareFeet: z.coerce.number().optional(),
        latitude: z.union([z.coerce.number(), z.string()]).optional(),
        longitude: z.union([z.coerce.number(), z.string()]).optional(),
        ownerId: z.string().optional(),
        createdBy: z.string().optional(),
        moderationStatus: z.string().optional(),
        status: z.string().optional(),
    })
};
