/**
 * listings.schema.ts — Listing validation schemas
 *
 * Enforces REGA advertising regulations (ضوابط الإعلانات العقارية):
 * Required fields for publication: title, city, district, propertyType,
 * price, area, REGA ad license number, FAL license number.
 */

import { z } from "zod";

export const listingSchemas = {
  create: z.object({
    title: z.string().min(1, "عنوان الإعلان مطلوب"),
    description: z.string().optional(),
    address: z.string().optional(),
    city: z.string().min(1, "المدينة مطلوبة"),
    state: z.string().optional(),
    zipCode: z.string().optional(),
    region: z.string().optional(),
    district: z.string().optional(),
    regionId: z.coerce.number().optional(),
    cityId: z.coerce.number().optional(),
    districtId: z.coerce.number().optional(),
    price: z.union([z.coerce.number(), z.string()]),
    propertyCategory: z.string().optional(),
    propertyType: z.string().min(1, "نوع العقار مطلوب"),
    listingType: z.string().optional(),
    bedrooms: z.coerce.number().optional(),
    bathrooms: z.coerce.number().optional(),
    livingRooms: z.coerce.number().optional(),
    squareFeet: z.coerce.number().optional(),
    latitude: z.union([z.coerce.number(), z.string()]).optional(),
    longitude: z.union([z.coerce.number(), z.string()]).optional(),
    features: z.array(z.string()).optional(),
    ownerId: z.string().optional(),
    createdBy: z.string().optional(),
    agentId: z.string().optional(),
    organizationId: z.string().optional(),
    moderationStatus: z.string().optional(),
    status: z.string().optional(),
    // ── REGA-mandated fields ──
    regaAdLicenseNumber: z.string().optional(),  // Required for publishing, optional for drafts
    falLicenseNumber: z.string().optional(),
    deedNumber: z.string().optional(),
    legalStatus: z.string().optional(),
    facadeDirection: z.string().optional(),
    buildingAge: z.coerce.number().optional(),
    nationalAddressBuildingNo: z.string().optional(),
    nationalAddressPostalCode: z.string().optional(),
    nationalAddressAdditionalNo: z.string().optional(),
    contactNumber: z.string().optional(),
  }),
  update: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    address: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zipCode: z.string().optional(),
    region: z.string().optional(),
    district: z.string().optional(),
    regionId: z.coerce.number().optional(),
    cityId: z.coerce.number().optional(),
    districtId: z.coerce.number().optional(),
    price: z.union([z.coerce.number(), z.string()]).optional(),
    propertyCategory: z.string().optional(),
    propertyType: z.string().optional(),
    listingType: z.string().optional(),
    bedrooms: z.coerce.number().optional(),
    bathrooms: z.coerce.number().optional(),
    squareFeet: z.coerce.number().optional(),
    latitude: z.union([z.coerce.number(), z.string()]).optional(),
    longitude: z.union([z.coerce.number(), z.string()]).optional(),
    ownerId: z.string().optional(),
    createdBy: z.string().optional(),
    moderationStatus: z.string().optional(),
    status: z.string().optional(),
    // ── REGA fields ──
    regaAdLicenseNumber: z.string().optional(),
    falLicenseNumber: z.string().optional(),
    deedNumber: z.string().optional(),
    legalStatus: z.string().optional(),
    facadeDirection: z.string().optional(),
    buildingAge: z.coerce.number().optional(),
    contactNumber: z.string().optional(),
  }),
};
